version: '3.4'

services:
  ratedb:
    container_name: ratedb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ratedb_mongo_data:/data/db
  rateapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://ratedb
      - DatabaseSettings__DatabaseName=RateDb
      - DatabaseSettings__CollectionName=Rates
      - ExternalProviderSettings__BaseUrl=https://sandbox-api.coinmarketcap.com
      - ExternalProviderSettings__RatePath=v1/cryptocurrency/listings/latest
      - ExternalProviderSettings__ApiKey=f25cb104-1984-4fe6-8c40-73b5517e9bbd
    ports:
      - 5001:80
    depends_on:
      - ratedb