version: '3.4'

services:
  ratedb:
    image: mongo
  rateapi:
    image: ${DOCKER_REGISTRY-}revixrateapi
    build:
      context: .
      dockerfile: Revix.Rate.API/Dockerfile

volumes:
  ratedb_mongo_data: